// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
  device_uid, 
  name, 
  firmware_version,
  firmware_build,
  last_update,
  ip_address,
  wifi_ssid,
  last_seen,
  status,
  user_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at
`

type CreateDeviceParams struct {
	DeviceUid       string         `json:"device_uid"`
	Name            string         `json:"name"`
	FirmwareVersion string         `json:"firmware_version"`
	FirmwareBuild   sql.NullString `json:"firmware_build"`
	LastUpdate      time.Time      `json:"last_update"`
	IpAddress       pqtype.Inet    `json:"ip_address"`
	WifiSsid        sql.NullString `json:"wifi_ssid"`
	LastSeen        sql.NullTime   `json:"last_seen"`
	Status          string         `json:"status"`
	UserID          sql.NullInt64  `json:"user_id"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.DeviceUid,
		arg.Name,
		arg.FirmwareVersion,
		arg.FirmwareBuild,
		arg.LastUpdate,
		arg.IpAddress,
		arg.WifiSsid,
		arg.LastSeen,
		arg.Status,
		arg.UserID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at FROM devices
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, argUuid uuid.UUID) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, argUuid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceForUpdate = `-- name: GetDeviceForUpdate :one
SELECT id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at FROM devices
WHERE uuid = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetDeviceForUpdate(ctx context.Context, argUuid uuid.UUID) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceForUpdate, argUuid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at FROM devices
WHERE user_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListDevicesParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DeviceUid,
			&i.Name,
			&i.FirmwareVersion,
			&i.FirmwareBuild,
			&i.LastUpdate,
			&i.IpAddress,
			&i.WifiSsid,
			&i.LastSeen,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevices = `-- name: UpdateDevices :one
UPDATE devices
set status = $2
WHERE uuid = $1
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at
`

type UpdateDevicesParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDevices(ctx context.Context, arg UpdateDevicesParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevices, arg.Uuid, arg.Status)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
