// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_telemetry_history.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDeviceSensorHistory = `-- name: CreateDeviceSensorHistory :one
INSERT INTO device_sensor_history (
    device_id,
    soil_moisture,
    temperature,
    battery
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, device_id, soil_moisture, temperature, battery, created_at
`

type CreateDeviceSensorHistoryParams struct {
	DeviceID     int64           `json:"device_id"`
	SoilMoisture int32           `json:"soil_moisture"`
	Temperature  sql.NullFloat64 `json:"temperature"`
	Battery      sql.NullInt32   `json:"battery"`
}

func (q *Queries) CreateDeviceSensorHistory(ctx context.Context, arg CreateDeviceSensorHistoryParams) (DeviceSensorHistory, error) {
	row := q.db.QueryRowContext(ctx, createDeviceSensorHistory,
		arg.DeviceID,
		arg.SoilMoisture,
		arg.Temperature,
		arg.Battery,
	)
	var i DeviceSensorHistory
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.SoilMoisture,
		&i.Temperature,
		&i.Battery,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDeviceSensorHistory = `-- name: GetLatestDeviceSensorHistory :one
SELECT id, device_id, soil_moisture, temperature, battery, created_at
FROM device_sensor_history
WHERE device_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDeviceSensorHistory(ctx context.Context, deviceID int64) (DeviceSensorHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeviceSensorHistory, deviceID)
	var i DeviceSensorHistory
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.SoilMoisture,
		&i.Temperature,
		&i.Battery,
		&i.CreatedAt,
	)
	return i, err
}

const listDeviceSensorHistory = `-- name: ListDeviceSensorHistory :many
SELECT id, device_id, soil_moisture, temperature, battery, created_at
FROM device_sensor_history
WHERE device_id = $1
  AND created_at >= $2
ORDER BY created_at ASC
`

type ListDeviceSensorHistoryParams struct {
	DeviceID  int64     `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListDeviceSensorHistory(ctx context.Context, arg ListDeviceSensorHistoryParams) ([]DeviceSensorHistory, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceSensorHistory, arg.DeviceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceSensorHistory{}
	for rows.Next() {
		var i DeviceSensorHistory
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.SoilMoisture,
			&i.Temperature,
			&i.Battery,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
