// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
  device_uid, 
  name, 
  firmware_version,
  firmware_build,
  last_update,
  ip_address,
  wifi_ssid,
  last_seen,
  status,
  user_id,
  qr_token,
  qr_code_file
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type CreateDeviceParams struct {
	DeviceUid       string         `json:"device_uid"`
	Name            string         `json:"name"`
	FirmwareVersion string         `json:"firmware_version"`
	FirmwareBuild   sql.NullString `json:"firmware_build"`
	LastUpdate      time.Time      `json:"last_update"`
	IpAddress       pqtype.Inet    `json:"ip_address"`
	WifiSsid        sql.NullString `json:"wifi_ssid"`
	LastSeen        sql.NullTime   `json:"last_seen"`
	Status          string         `json:"status"`
	UserID          sql.NullInt64  `json:"user_id"`
	QrToken         string         `json:"qr_token"`
	QrCodeFile      sql.NullString `json:"qr_code_file"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.DeviceUid,
		arg.Name,
		arg.FirmwareVersion,
		arg.FirmwareBuild,
		arg.LastUpdate,
		arg.IpAddress,
		arg.WifiSsid,
		arg.LastSeen,
		arg.Status,
		arg.UserID,
		arg.QrToken,
		arg.QrCodeFile,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture FROM devices
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, argUuid uuid.UUID) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, argUuid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const getDeviceByUID = `-- name: GetDeviceByUID :one
SELECT id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture FROM devices
WHERE device_uid = $1 LIMIT 1
`

func (q *Queries) GetDeviceByUID(ctx context.Context, deviceUid string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByUID, deviceUid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const getDeviceForUpdate = `-- name: GetDeviceForUpdate :one
SELECT id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture FROM devices
WHERE uuid = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetDeviceForUpdate(ctx context.Context, argUuid uuid.UUID) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceForUpdate, argUuid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const linkDeviceToUserByQrToken = `-- name: LinkDeviceToUserByQrToken :one
UPDATE devices
SET user_id = $2
WHERE qr_token = $1 AND user_id IS NULL
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type LinkDeviceToUserByQrTokenParams struct {
	QrToken string        `json:"qr_token"`
	UserID  sql.NullInt64 `json:"user_id"`
}

func (q *Queries) LinkDeviceToUserByQrToken(ctx context.Context, arg LinkDeviceToUserByQrTokenParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, linkDeviceToUserByQrToken, arg.QrToken, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture FROM devices
WHERE user_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListDevicesParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DeviceUid,
			&i.Name,
			&i.FirmwareVersion,
			&i.FirmwareBuild,
			&i.LastUpdate,
			&i.IpAddress,
			&i.WifiSsid,
			&i.LastSeen,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.QrToken,
			&i.QrCodeFile,
			&i.IsOnline,
			&i.IsIrrigating,
			&i.SoilMoisture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkDeviceFromUser = `-- name: UnlinkDeviceFromUser :one
UPDATE devices
SET user_id = NULL
WHERE uuid = $1 AND user_id = $2
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type UnlinkDeviceFromUserParams struct {
	Uuid   uuid.UUID     `json:"uuid"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) UnlinkDeviceFromUser(ctx context.Context, arg UnlinkDeviceFromUserParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, unlinkDeviceFromUser, arg.Uuid, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const updateDeviceRegistration = `-- name: UpdateDeviceRegistration :one
UPDATE devices
SET
    firmware_version = $2,
    firmware_build = $3,
    ip_address = $4,
    wifi_ssid = $5,
    status = $6,
    last_seen = NOW()
WHERE device_uid = $1
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type UpdateDeviceRegistrationParams struct {
	DeviceUid       string         `json:"device_uid"`
	FirmwareVersion string         `json:"firmware_version"`
	FirmwareBuild   sql.NullString `json:"firmware_build"`
	IpAddress       pqtype.Inet    `json:"ip_address"`
	WifiSsid        sql.NullString `json:"wifi_ssid"`
	Status          string         `json:"status"`
}

func (q *Queries) UpdateDeviceRegistration(ctx context.Context, arg UpdateDeviceRegistrationParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceRegistration,
		arg.DeviceUid,
		arg.FirmwareVersion,
		arg.FirmwareBuild,
		arg.IpAddress,
		arg.WifiSsid,
		arg.Status,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const updateDeviceState = `-- name: UpdateDeviceState :one
UPDATE devices
SET
    is_online = $2, 
    is_irrigating = $3
WHERE device_uid = $1
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type UpdateDeviceStateParams struct {
	DeviceUid    string `json:"device_uid"`
	IsOnline     bool   `json:"is_online"`
	IsIrrigating bool   `json:"is_irrigating"`
}

func (q *Queries) UpdateDeviceState(ctx context.Context, arg UpdateDeviceStateParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceState, arg.DeviceUid, arg.IsOnline, arg.IsIrrigating)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const updateDeviceTelemetryByUID = `-- name: UpdateDeviceTelemetryByUID :one
UPDATE devices
SET
    last_seen = $2,
    status = $3,
    ip_address = $4,
    wifi_ssid = $5,
    soil_moisture = $6
WHERE device_uid = $1
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type UpdateDeviceTelemetryByUIDParams struct {
	DeviceUid    string         `json:"device_uid"`
	LastSeen     sql.NullTime   `json:"last_seen"`
	Status       string         `json:"status"`
	IpAddress    pqtype.Inet    `json:"ip_address"`
	WifiSsid     sql.NullString `json:"wifi_ssid"`
	SoilMoisture sql.NullInt32  `json:"soil_moisture"`
}

func (q *Queries) UpdateDeviceTelemetryByUID(ctx context.Context, arg UpdateDeviceTelemetryByUIDParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceTelemetryByUID,
		arg.DeviceUid,
		arg.LastSeen,
		arg.Status,
		arg.IpAddress,
		arg.WifiSsid,
		arg.SoilMoisture,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const updateDevices = `-- name: UpdateDevices :one
UPDATE devices
set status = $2
WHERE uuid = $1
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type UpdateDevicesParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDevices(ctx context.Context, arg UpdateDevicesParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevices, arg.Uuid, arg.Status)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}

const updateNameDevice = `-- name: UpdateNameDevice :one
UPDATE devices
set name = $2
WHERE uuid = $1
RETURNING id, uuid, device_uid, name, firmware_version, firmware_build, last_update, ip_address, wifi_ssid, last_seen, status, user_id, created_at, qr_token, qr_code_file, is_online, is_irrigating, soil_moisture
`

type UpdateNameDeviceParams struct {
	Uuid uuid.UUID `json:"uuid"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateNameDevice(ctx context.Context, arg UpdateNameDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateNameDevice, arg.Uuid, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceUid,
		&i.Name,
		&i.FirmwareVersion,
		&i.FirmwareBuild,
		&i.LastUpdate,
		&i.IpAddress,
		&i.WifiSsid,
		&i.LastSeen,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.QrToken,
		&i.QrCodeFile,
		&i.IsOnline,
		&i.IsIrrigating,
		&i.SoilMoisture,
	)
	return i, err
}
