// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: faqs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFaq = `-- name: GetFaq :one
SELECT id, uuid, question, answer, category, published, order_number, created_at FROM faqs
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetFaq(ctx context.Context, argUuid uuid.UUID) (Faq, error) {
	row := q.db.QueryRowContext(ctx, getFaq, argUuid)
	var i Faq
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Question,
		&i.Answer,
		&i.Category,
		&i.Published,
		&i.OrderNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listFaqs = `-- name: ListFaqs :many
SELECT id, uuid, question, answer, category, published, order_number, created_at
FROM faqs
WHERE published = true
ORDER BY order_number ASC
LIMIT $1
OFFSET $2
`

type ListFaqsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFaqs(ctx context.Context, arg ListFaqsParams) ([]Faq, error) {
	rows, err := q.db.QueryContext(ctx, listFaqs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Faq{}
	for rows.Next() {
		var i Faq
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Question,
			&i.Answer,
			&i.Category,
			&i.Published,
			&i.OrderNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
