// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: help_contents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getHelpContent = `-- name: GetHelpContent :one
SELECT id, uuid, title, slug, category, content, image_url, published, order_number, created_at, updated_at FROM help_contents
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetHelpContent(ctx context.Context, argUuid uuid.UUID) (HelpContent, error) {
	row := q.db.QueryRowContext(ctx, getHelpContent, argUuid)
	var i HelpContent
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Slug,
		&i.Category,
		&i.Content,
		&i.ImageUrl,
		&i.Published,
		&i.OrderNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHelpContents = `-- name: ListHelpContents :many
SELECT id, uuid, title, slug, category, content, image_url, published, order_number, created_at, updated_at
FROM help_contents
WHERE published = true
ORDER BY order_number ASC
LIMIT $1
OFFSET $2
`

type ListHelpContentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListHelpContents(ctx context.Context, arg ListHelpContentsParams) ([]HelpContent, error) {
	rows, err := q.db.QueryContext(ctx, listHelpContents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HelpContent{}
	for rows.Next() {
		var i HelpContent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Slug,
			&i.Category,
			&i.Content,
			&i.ImageUrl,
			&i.Published,
			&i.OrderNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHelpContentsByCategory = `-- name: ListHelpContentsByCategory :many
SELECT id, uuid, title, slug, category, content, image_url, published, order_number, created_at, updated_at
FROM help_contents
WHERE category = $1
AND published = true
ORDER BY order_number ASC
LIMIT $2
OFFSET $3
`

type ListHelpContentsByCategoryParams struct {
	Category string `json:"category"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListHelpContentsByCategory(ctx context.Context, arg ListHelpContentsByCategoryParams) ([]HelpContent, error) {
	rows, err := q.db.QueryContext(ctx, listHelpContentsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HelpContent{}
	for rows.Next() {
		var i HelpContent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Slug,
			&i.Category,
			&i.Content,
			&i.ImageUrl,
			&i.Published,
			&i.OrderNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
