// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: irrigation_schedule.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createIrrigationSchedule = `-- name: CreateIrrigationSchedule :one
INSERT INTO irrigation_schedules (
    device_id,
    user_id,
    name,
    enabled,
    start_time,
    duration_seconds,
    days_of_week
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uuid, device_id, user_id, name, enabled, start_time, duration_seconds, days_of_week, created_at, updated_at
`

type CreateIrrigationScheduleParams struct {
	DeviceID        int64          `json:"device_id"`
	UserID          int64          `json:"user_id"`
	Name            sql.NullString `json:"name"`
	Enabled         bool           `json:"enabled"`
	StartTime       time.Time      `json:"start_time"`
	DurationSeconds int32          `json:"duration_seconds"`
	DaysOfWeek      string         `json:"days_of_week"`
}

func (q *Queries) CreateIrrigationSchedule(ctx context.Context, arg CreateIrrigationScheduleParams) (IrrigationSchedule, error) {
	row := q.db.QueryRowContext(ctx, createIrrigationSchedule,
		arg.DeviceID,
		arg.UserID,
		arg.Name,
		arg.Enabled,
		arg.StartTime,
		arg.DurationSeconds,
		arg.DaysOfWeek,
	)
	var i IrrigationSchedule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.StartTime,
		&i.DurationSeconds,
		&i.DaysOfWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIrrigationSchedule = `-- name: DeleteIrrigationSchedule :one
DELETE FROM irrigation_schedules
WHERE uuid = $1 AND user_id = $2
RETURNING uuid
`

type DeleteIrrigationScheduleParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) DeleteIrrigationSchedule(ctx context.Context, arg DeleteIrrigationScheduleParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteIrrigationSchedule, arg.Uuid, arg.UserID)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const getIrrigationSchedule = `-- name: GetIrrigationSchedule :one
SELECT id, uuid, device_id, user_id, name, enabled, start_time, duration_seconds, days_of_week, created_at, updated_at
FROM irrigation_schedules
WHERE uuid = $1 AND user_id = $2
LIMIT 1
`

type GetIrrigationScheduleParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) GetIrrigationSchedule(ctx context.Context, arg GetIrrigationScheduleParams) (IrrigationSchedule, error) {
	row := q.db.QueryRowContext(ctx, getIrrigationSchedule, arg.Uuid, arg.UserID)
	var i IrrigationSchedule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.StartTime,
		&i.DurationSeconds,
		&i.DaysOfWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIrrigationSchedules = `-- name: ListIrrigationSchedules :many
SELECT id, uuid, device_id, user_id, name, enabled, start_time, duration_seconds, days_of_week, created_at, updated_at
FROM irrigation_schedules
WHERE user_id = $1
ORDER BY start_time, id
`

func (q *Queries) ListIrrigationSchedules(ctx context.Context, userID int64) ([]IrrigationSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listIrrigationSchedules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IrrigationSchedule{}
	for rows.Next() {
		var i IrrigationSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DeviceID,
			&i.UserID,
			&i.Name,
			&i.Enabled,
			&i.StartTime,
			&i.DurationSeconds,
			&i.DaysOfWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIrrigationSchedule = `-- name: UpdateIrrigationSchedule :one
UPDATE irrigation_schedules
SET name = $3,
    enabled = $4,
    start_time = $5,
    duration_seconds = $6,
    days_of_week = $7,
    updated_at = now()
WHERE uuid = $1 AND user_id = $2
RETURNING id, uuid, device_id, user_id, name, enabled, start_time, duration_seconds, days_of_week, created_at, updated_at
`

type UpdateIrrigationScheduleParams struct {
	Uuid            uuid.UUID      `json:"uuid"`
	UserID          int64          `json:"user_id"`
	Name            sql.NullString `json:"name"`
	Enabled         bool           `json:"enabled"`
	StartTime       time.Time      `json:"start_time"`
	DurationSeconds int32          `json:"duration_seconds"`
	DaysOfWeek      string         `json:"days_of_week"`
}

func (q *Queries) UpdateIrrigationSchedule(ctx context.Context, arg UpdateIrrigationScheduleParams) (IrrigationSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateIrrigationSchedule,
		arg.Uuid,
		arg.UserID,
		arg.Name,
		arg.Enabled,
		arg.StartTime,
		arg.DurationSeconds,
		arg.DaysOfWeek,
	)
	var i IrrigationSchedule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.StartTime,
		&i.DurationSeconds,
		&i.DaysOfWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
