// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: irrigation_action.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createIrrigationAction = `-- name: CreateIrrigationAction :one
INSERT INTO irrigation_actions (
  device_id, 
  user_id, 
  started_at,
  finished_at,
  duration_seconds,
  status,
  trigger_type,
  water_volume_ml,
  error_message
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, uuid, device_id, user_id, started_at, finished_at, duration_seconds, status, trigger_type, water_volume_ml, error_message, created_at
`

type CreateIrrigationActionParams struct {
	DeviceID        int64          `json:"device_id"`
	UserID          int64          `json:"user_id"`
	StartedAt       time.Time      `json:"started_at"`
	FinishedAt      sql.NullTime   `json:"finished_at"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	TriggerType     string         `json:"trigger_type"`
	WaterVolumeMl   sql.NullInt32  `json:"water_volume_ml"`
	ErrorMessage    sql.NullString `json:"error_message"`
}

func (q *Queries) CreateIrrigationAction(ctx context.Context, arg CreateIrrigationActionParams) (IrrigationAction, error) {
	row := q.db.QueryRowContext(ctx, createIrrigationAction,
		arg.DeviceID,
		arg.UserID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationSeconds,
		arg.Status,
		arg.TriggerType,
		arg.WaterVolumeMl,
		arg.ErrorMessage,
	)
	var i IrrigationAction
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationSeconds,
		&i.Status,
		&i.TriggerType,
		&i.WaterVolumeMl,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIrrigationAction = `-- name: DeleteIrrigationAction :exec
DELETE FROM irrigation_actions WHERE id = $1
`

func (q *Queries) DeleteIrrigationAction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIrrigationAction, id)
	return err
}

const getIrrigationAction = `-- name: GetIrrigationAction :one
SELECT id, uuid, device_id, user_id, started_at, finished_at, duration_seconds, status, trigger_type, water_volume_ml, error_message, created_at FROM irrigation_actions
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetIrrigationAction(ctx context.Context, argUuid uuid.UUID) (IrrigationAction, error) {
	row := q.db.QueryRowContext(ctx, getIrrigationAction, argUuid)
	var i IrrigationAction
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationSeconds,
		&i.Status,
		&i.TriggerType,
		&i.WaterVolumeMl,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listIrrigationAction = `-- name: ListIrrigationAction :many
SELECT id, uuid, device_id, user_id, started_at, finished_at, duration_seconds, status, trigger_type, water_volume_ml, error_message, created_at FROM irrigation_actions
WHERE user_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListIrrigationActionParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIrrigationAction(ctx context.Context, arg ListIrrigationActionParams) ([]IrrigationAction, error) {
	rows, err := q.db.QueryContext(ctx, listIrrigationAction, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IrrigationAction{}
	for rows.Next() {
		var i IrrigationAction
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DeviceID,
			&i.UserID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationSeconds,
			&i.Status,
			&i.TriggerType,
			&i.WaterVolumeMl,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIrrigationAction = `-- name: UpdateIrrigationAction :one
UPDATE irrigation_actions
SET
  finished_at = $2,
  duration_seconds = $3,
  status = $4,
  water_volume_ml = $5,
  error_message = $6
WHERE uuid = $1
RETURNING id, uuid, device_id, user_id, started_at, finished_at, duration_seconds, status, trigger_type, water_volume_ml, error_message, created_at
`

type UpdateIrrigationActionParams struct {
	Uuid            uuid.UUID      `json:"uuid"`
	FinishedAt      sql.NullTime   `json:"finished_at"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	WaterVolumeMl   sql.NullInt32  `json:"water_volume_ml"`
	ErrorMessage    sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateIrrigationAction(ctx context.Context, arg UpdateIrrigationActionParams) (IrrigationAction, error) {
	row := q.db.QueryRowContext(ctx, updateIrrigationAction,
		arg.Uuid,
		arg.FinishedAt,
		arg.DurationSeconds,
		arg.Status,
		arg.WaterVolumeMl,
		arg.ErrorMessage,
	)
	var i IrrigationAction
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationSeconds,
		&i.Status,
		&i.TriggerType,
		&i.WaterVolumeMl,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}
