// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: irrigation_command.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createIrrigationCommand = `-- name: CreateIrrigationCommand :one
INSERT INTO irrigation_commands (
    device_id,
    user_id,
    action,
    duration_seconds
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, uuid, device_id, user_id, action, duration_seconds, status, error_message, requested_at, processed_at, created_at
`

type CreateIrrigationCommandParams struct {
	DeviceID        int64         `json:"device_id"`
	UserID          int64         `json:"user_id"`
	Action          string        `json:"action"`
	DurationSeconds sql.NullInt32 `json:"duration_seconds"`
}

func (q *Queries) CreateIrrigationCommand(ctx context.Context, arg CreateIrrigationCommandParams) (IrrigationCommand, error) {
	row := q.db.QueryRowContext(ctx, createIrrigationCommand,
		arg.DeviceID,
		arg.UserID,
		arg.Action,
		arg.DurationSeconds,
	)
	var i IrrigationCommand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.Action,
		&i.DurationSeconds,
		&i.Status,
		&i.ErrorMessage,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIrrigationCommand = `-- name: DeleteIrrigationCommand :exec
DELETE
FROM irrigation_commands
WHERE uuid = $1
`

func (q *Queries) DeleteIrrigationCommand(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIrrigationCommand, argUuid)
	return err
}

const existsPendingIrrigationCommand = `-- name: ExistsPendingIrrigationCommand :one
SELECT EXISTS (
    SELECT 1
    FROM irrigation_commands
    WHERE device_id = $1
      AND status = 'PENDING'
)
`

func (q *Queries) ExistsPendingIrrigationCommand(ctx context.Context, deviceID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsPendingIrrigationCommand, deviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const failTimedOutCommands = `-- name: FailTimedOutCommands :exec
UPDATE irrigation_commands
SET
    status = 'TIMEOUT',
    processed_at = now(),
    error_message = 'Device timeout'
WHERE
    status = 'PENDING'
    AND requested_at <= now() - interval '10 seconds'
`

func (q *Queries) FailTimedOutCommands(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, failTimedOutCommands)
	return err
}

const getIrrigationCommand = `-- name: GetIrrigationCommand :one
SELECT id, uuid, device_id, user_id, action, duration_seconds, status, error_message, requested_at, processed_at, created_at
FROM irrigation_commands
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) GetIrrigationCommand(ctx context.Context, argUuid uuid.UUID) (IrrigationCommand, error) {
	row := q.db.QueryRowContext(ctx, getIrrigationCommand, argUuid)
	var i IrrigationCommand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.Action,
		&i.DurationSeconds,
		&i.Status,
		&i.ErrorMessage,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listIrrigationCommands = `-- name: ListIrrigationCommands :many
SELECT id, uuid, device_id, user_id, action, duration_seconds, status, error_message, requested_at, processed_at, created_at
FROM irrigation_commands
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListIrrigationCommandsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIrrigationCommands(ctx context.Context, arg ListIrrigationCommandsParams) ([]IrrigationCommand, error) {
	rows, err := q.db.QueryContext(ctx, listIrrigationCommands, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IrrigationCommand{}
	for rows.Next() {
		var i IrrigationCommand
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DeviceID,
			&i.UserID,
			&i.Action,
			&i.DurationSeconds,
			&i.Status,
			&i.ErrorMessage,
			&i.RequestedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIrrigationCommandStatus = `-- name: UpdateIrrigationCommandStatus :one
UPDATE irrigation_commands
SET
    status = $2,
    error_message = $3,
    processed_at = now()
WHERE uuid = $1 AND status = 'PENDING'
RETURNING id, uuid, device_id, user_id, action, duration_seconds, status, error_message, requested_at, processed_at, created_at
`

type UpdateIrrigationCommandStatusParams struct {
	Uuid         uuid.UUID      `json:"uuid"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateIrrigationCommandStatus(ctx context.Context, arg UpdateIrrigationCommandStatusParams) (IrrigationCommand, error) {
	row := q.db.QueryRowContext(ctx, updateIrrigationCommandStatus, arg.Uuid, arg.Status, arg.ErrorMessage)
	var i IrrigationCommand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.UserID,
		&i.Action,
		&i.DurationSeconds,
		&i.Status,
		&i.ErrorMessage,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}
