// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: irrigation_preferences.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createIrrigationPreferences = `-- name: CreateIrrigationPreferences :one
INSERT INTO irrigation_preferences (
  device_id, 
  irrigation_mode,
  moisture_threshold,
  dry_time_minutes,
  max_irrigations_per_day,
  start_hour,
  end_hour
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, uuid, device_id, enabled, irrigation_mode, moisture_threshold, dry_time_minutes, irrigation_duration_seconds, max_irrigations_per_day, start_hour, end_hour, created_at, updated_at
`

type CreateIrrigationPreferencesParams struct {
	DeviceID             int64        `json:"device_id"`
	IrrigationMode       string       `json:"irrigation_mode"`
	MoistureThreshold    int32        `json:"moisture_threshold"`
	DryTimeMinutes       int32        `json:"dry_time_minutes"`
	MaxIrrigationsPerDay int32        `json:"max_irrigations_per_day"`
	StartHour            sql.NullTime `json:"start_hour"`
	EndHour              sql.NullTime `json:"end_hour"`
}

func (q *Queries) CreateIrrigationPreferences(ctx context.Context, arg CreateIrrigationPreferencesParams) (IrrigationPreference, error) {
	row := q.db.QueryRowContext(ctx, createIrrigationPreferences,
		arg.DeviceID,
		arg.IrrigationMode,
		arg.MoistureThreshold,
		arg.DryTimeMinutes,
		arg.MaxIrrigationsPerDay,
		arg.StartHour,
		arg.EndHour,
	)
	var i IrrigationPreference
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.Enabled,
		&i.IrrigationMode,
		&i.MoistureThreshold,
		&i.DryTimeMinutes,
		&i.IrrigationDurationSeconds,
		&i.MaxIrrigationsPerDay,
		&i.StartHour,
		&i.EndHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIrrigationPreference = `-- name: DeleteIrrigationPreference :exec
DELETE FROM irrigation_preferences WHERE uuid = $1
`

func (q *Queries) DeleteIrrigationPreference(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIrrigationPreference, argUuid)
	return err
}

const deleteIrrigationPreferenceByDeviceId = `-- name: DeleteIrrigationPreferenceByDeviceId :exec
DELETE FROM irrigation_preferences WHERE device_id = $1
`

func (q *Queries) DeleteIrrigationPreferenceByDeviceId(ctx context.Context, deviceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIrrigationPreferenceByDeviceId, deviceID)
	return err
}

const getIrrigationPreference = `-- name: GetIrrigationPreference :one
SELECT id, uuid, device_id, enabled, irrigation_mode, moisture_threshold, dry_time_minutes, irrigation_duration_seconds, max_irrigations_per_day, start_hour, end_hour, created_at, updated_at FROM irrigation_preferences
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetIrrigationPreference(ctx context.Context, argUuid uuid.UUID) (IrrigationPreference, error) {
	row := q.db.QueryRowContext(ctx, getIrrigationPreference, argUuid)
	var i IrrigationPreference
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.Enabled,
		&i.IrrigationMode,
		&i.MoistureThreshold,
		&i.DryTimeMinutes,
		&i.IrrigationDurationSeconds,
		&i.MaxIrrigationsPerDay,
		&i.StartHour,
		&i.EndHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIrrigationPreferenceByDevice = `-- name: GetIrrigationPreferenceByDevice :one
SELECT id, uuid, device_id, enabled, irrigation_mode, moisture_threshold, dry_time_minutes, irrigation_duration_seconds, max_irrigations_per_day, start_hour, end_hour, created_at, updated_at FROM irrigation_preferences 
WHERE device_id = $1 LIMIT 1
`

func (q *Queries) GetIrrigationPreferenceByDevice(ctx context.Context, deviceID int64) (IrrigationPreference, error) {
	row := q.db.QueryRowContext(ctx, getIrrigationPreferenceByDevice, deviceID)
	var i IrrigationPreference
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.Enabled,
		&i.IrrigationMode,
		&i.MoistureThreshold,
		&i.DryTimeMinutes,
		&i.IrrigationDurationSeconds,
		&i.MaxIrrigationsPerDay,
		&i.StartHour,
		&i.EndHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIrrigationPreferences = `-- name: ListIrrigationPreferences :many
SELECT id, uuid, device_id, enabled, irrigation_mode, moisture_threshold, dry_time_minutes, irrigation_duration_seconds, max_irrigations_per_day, start_hour, end_hour, created_at, updated_at FROM irrigation_preferences
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListIrrigationPreferencesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIrrigationPreferences(ctx context.Context, arg ListIrrigationPreferencesParams) ([]IrrigationPreference, error) {
	rows, err := q.db.QueryContext(ctx, listIrrigationPreferences, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IrrigationPreference{}
	for rows.Next() {
		var i IrrigationPreference
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DeviceID,
			&i.Enabled,
			&i.IrrigationMode,
			&i.MoistureThreshold,
			&i.DryTimeMinutes,
			&i.IrrigationDurationSeconds,
			&i.MaxIrrigationsPerDay,
			&i.StartHour,
			&i.EndHour,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIrrigationPreference = `-- name: UpdateIrrigationPreference :one
UPDATE irrigation_preferences
SET
  enabled = COALESCE($1, enabled),
  irrigation_mode = COALESCE($2, irrigation_mode),
  moisture_threshold = COALESCE($3, moisture_threshold),
  dry_time_minutes = COALESCE($4, dry_time_minutes),
  irrigation_duration_seconds = COALESCE($5, irrigation_duration_seconds),
  max_irrigations_per_day = COALESCE($6, max_irrigations_per_day),
  start_hour = COALESCE($7, start_hour),
  end_hour = COALESCE($8, end_hour),
  updated_at = now()
WHERE uuid = $9
RETURNING id, uuid, device_id, enabled, irrigation_mode, moisture_threshold, dry_time_minutes, irrigation_duration_seconds, max_irrigations_per_day, start_hour, end_hour, created_at, updated_at
`

type UpdateIrrigationPreferenceParams struct {
	Enabled                   sql.NullBool   `json:"enabled"`
	IrrigationMode            sql.NullString `json:"irrigation_mode"`
	MoistureThreshold         sql.NullInt32  `json:"moisture_threshold"`
	DryTimeMinutes            sql.NullInt32  `json:"dry_time_minutes"`
	IrrigationDurationSeconds sql.NullInt32  `json:"irrigation_duration_seconds"`
	MaxIrrigationsPerDay      sql.NullInt32  `json:"max_irrigations_per_day"`
	StartHour                 sql.NullTime   `json:"start_hour"`
	EndHour                   sql.NullTime   `json:"end_hour"`
	Uuid                      uuid.UUID      `json:"uuid"`
}

func (q *Queries) UpdateIrrigationPreference(ctx context.Context, arg UpdateIrrigationPreferenceParams) (IrrigationPreference, error) {
	row := q.db.QueryRowContext(ctx, updateIrrigationPreference,
		arg.Enabled,
		arg.IrrigationMode,
		arg.MoistureThreshold,
		arg.DryTimeMinutes,
		arg.IrrigationDurationSeconds,
		arg.MaxIrrigationsPerDay,
		arg.StartHour,
		arg.EndHour,
		arg.Uuid,
	)
	var i IrrigationPreference
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DeviceID,
		&i.Enabled,
		&i.IrrigationMode,
		&i.MoistureThreshold,
		&i.DryTimeMinutes,
		&i.IrrigationDurationSeconds,
		&i.MaxIrrigationsPerDay,
		&i.StartHour,
		&i.EndHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
