// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: irrigation_preferences_history.sql

package db

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

const createIrrigationPreferencesHistory = `-- name: CreateIrrigationPreferencesHistory :one
INSERT INTO irrigation_preferences_history (
  preference_id, 
  user_id,
  old_data,
  new_data
) VALUES (
  $1, $2, $3, $4
) RETURNING id, preference_id, user_id, old_data, new_data, changed_at
`

type CreateIrrigationPreferencesHistoryParams struct {
	PreferenceID int64                 `json:"preference_id"`
	UserID       int64                 `json:"user_id"`
	OldData      pqtype.NullRawMessage `json:"old_data"`
	NewData      pqtype.NullRawMessage `json:"new_data"`
}

func (q *Queries) CreateIrrigationPreferencesHistory(ctx context.Context, arg CreateIrrigationPreferencesHistoryParams) (IrrigationPreferencesHistory, error) {
	row := q.db.QueryRowContext(ctx, createIrrigationPreferencesHistory,
		arg.PreferenceID,
		arg.UserID,
		arg.OldData,
		arg.NewData,
	)
	var i IrrigationPreferencesHistory
	err := row.Scan(
		&i.ID,
		&i.PreferenceID,
		&i.UserID,
		&i.OldData,
		&i.NewData,
		&i.ChangedAt,
	)
	return i, err
}
