// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legal_documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getLegalDocument = `-- name: GetLegalDocument :one
SELECT id, uuid, type, version, title, content, active, published_at, created_at
FROM legal_documents
WHERE uuid = $1
AND active = true
LIMIT 1
`

func (q *Queries) GetLegalDocument(ctx context.Context, argUuid uuid.UUID) (LegalDocument, error) {
	row := q.db.QueryRowContext(ctx, getLegalDocument, argUuid)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Type,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.Active,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLegalDocuments = `-- name: ListLegalDocuments :many
SELECT id, uuid, type, version, title, content, active, published_at, created_at
FROM legal_documents
WHERE active = true
ORDER BY published_at DESC
LIMIT $1
OFFSET $2
`

type ListLegalDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLegalDocuments(ctx context.Context, arg ListLegalDocumentsParams) ([]LegalDocument, error) {
	rows, err := q.db.QueryContext(ctx, listLegalDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalDocument{}
	for rows.Next() {
		var i LegalDocument
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Type,
			&i.Version,
			&i.Title,
			&i.Content,
			&i.Active,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
