// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Device struct {
	ID              int64          `json:"id"`
	Uuid            uuid.UUID      `json:"uuid"`
	DeviceUid       string         `json:"device_uid"`
	Name            string         `json:"name"`
	FirmwareVersion string         `json:"firmware_version"`
	FirmwareBuild   sql.NullString `json:"firmware_build"`
	LastUpdate      time.Time      `json:"last_update"`
	IpAddress       pqtype.Inet    `json:"ip_address"`
	WifiSsid        sql.NullString `json:"wifi_ssid"`
	LastSeen        sql.NullTime   `json:"last_seen"`
	Status          string         `json:"status"`
	UserID          sql.NullInt64  `json:"user_id"`
	CreatedAt       time.Time      `json:"created_at"`
	QrToken         string         `json:"qr_token"`
	QrCodeFile      sql.NullString `json:"qr_code_file"`
}

type IrrigationAction struct {
	ID              int64          `json:"id"`
	Uuid            uuid.UUID      `json:"uuid"`
	DeviceID        int64          `json:"device_id"`
	UserID          int64          `json:"user_id"`
	StartedAt       time.Time      `json:"started_at"`
	FinishedAt      sql.NullTime   `json:"finished_at"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	TriggerType     string         `json:"trigger_type"`
	WaterVolumeMl   sql.NullInt32  `json:"water_volume_ml"`
	ErrorMessage    sql.NullString `json:"error_message"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID                int64          `json:"id"`
	Uuid              uuid.UUID      `json:"uuid"`
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	FullName          string         `json:"full_name"`
	Email             string         `json:"email"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	ProfileImage      sql.NullString `json:"profile_image"`
}
