// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Device struct {
	ID              int64          `json:"id"`
	Uuid            uuid.NullUUID  `json:"uuid"`
	DeviceUid       string         `json:"device_uid"`
	Name            string         `json:"name"`
	FirmwareVersion string         `json:"firmware_version"`
	FirmwareBuild   sql.NullString `json:"firmware_build"`
	LastUpdate      time.Time      `json:"last_update"`
	IpAddress       pqtype.Inet    `json:"ip_address"`
	WifiSsid        sql.NullString `json:"wifi_ssid"`
	LastSeen        sql.NullTime   `json:"last_seen"`
	Status          string         `json:"status"`
	UserID          sql.NullInt64  `json:"user_id"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID                int64         `json:"id"`
	Uuid              uuid.NullUUID `json:"uuid"`
	Username          string        `json:"username"`
	HashedPassword    string        `json:"hashed_password"`
	FullName          string        `json:"full_name"`
	Email             string        `json:"email"`
	PasswordChangedAt time.Time     `json:"password_changed_at"`
	CreatedAt         time.Time     `json:"created_at"`
}
