// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Device struct {
	ID              int64          `json:"id"`
	Uuid            uuid.UUID      `json:"uuid"`
	DeviceUid       string         `json:"device_uid"`
	Name            string         `json:"name"`
	FirmwareVersion string         `json:"firmware_version"`
	FirmwareBuild   sql.NullString `json:"firmware_build"`
	LastUpdate      time.Time      `json:"last_update"`
	IpAddress       pqtype.Inet    `json:"ip_address"`
	WifiSsid        sql.NullString `json:"wifi_ssid"`
	LastSeen        sql.NullTime   `json:"last_seen"`
	Status          string         `json:"status"`
	UserID          sql.NullInt64  `json:"user_id"`
	CreatedAt       time.Time      `json:"created_at"`
	QrToken         string         `json:"qr_token"`
	QrCodeFile      sql.NullString `json:"qr_code_file"`
}

type Faq struct {
	ID          int64          `json:"id"`
	Uuid        uuid.UUID      `json:"uuid"`
	Question    string         `json:"question"`
	Answer      string         `json:"answer"`
	Category    sql.NullString `json:"category"`
	Published   bool           `json:"published"`
	OrderNumber int32          `json:"order_number"`
	CreatedAt   time.Time      `json:"created_at"`
}

type HelpContent struct {
	ID          int64          `json:"id"`
	Uuid        uuid.UUID      `json:"uuid"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Category    string         `json:"category"`
	Content     string         `json:"content"`
	ImageUrl    sql.NullString `json:"image_url"`
	Published   bool           `json:"published"`
	OrderNumber int32          `json:"order_number"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type IrrigationAction struct {
	ID              int64          `json:"id"`
	Uuid            uuid.UUID      `json:"uuid"`
	DeviceID        int64          `json:"device_id"`
	UserID          int64          `json:"user_id"`
	StartedAt       time.Time      `json:"started_at"`
	FinishedAt      sql.NullTime   `json:"finished_at"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	TriggerType     string         `json:"trigger_type"`
	WaterVolumeMl   sql.NullInt32  `json:"water_volume_ml"`
	ErrorMessage    sql.NullString `json:"error_message"`
	CreatedAt       time.Time      `json:"created_at"`
}

type IrrigationPreference struct {
	ID                        int64        `json:"id"`
	Uuid                      uuid.UUID    `json:"uuid"`
	DeviceID                  int64        `json:"device_id"`
	Enabled                   bool         `json:"enabled"`
	IrrigationMode            string       `json:"irrigation_mode"`
	MoistureThreshold         int32        `json:"moisture_threshold"`
	DryTimeMinutes            int32        `json:"dry_time_minutes"`
	IrrigationDurationSeconds int32        `json:"irrigation_duration_seconds"`
	MaxIrrigationsPerDay      int32        `json:"max_irrigations_per_day"`
	StartHour                 sql.NullTime `json:"start_hour"`
	EndHour                   sql.NullTime `json:"end_hour"`
	CreatedAt                 time.Time    `json:"created_at"`
	UpdatedAt                 time.Time    `json:"updated_at"`
}

type IrrigationPreferencesHistory struct {
	ID           int64                 `json:"id"`
	PreferenceID int64                 `json:"preference_id"`
	UserID       int64                 `json:"user_id"`
	OldData      pqtype.NullRawMessage `json:"old_data"`
	NewData      pqtype.NullRawMessage `json:"new_data"`
	ChangedAt    time.Time             `json:"changed_at"`
}

type LegalDocument struct {
	ID          int64     `json:"id"`
	Uuid        uuid.UUID `json:"uuid"`
	Type        string    `json:"type"`
	Version     string    `json:"version"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	Active      bool      `json:"active"`
	PublishedAt time.Time `json:"published_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type Tutorial struct {
	ID          int64          `json:"id"`
	Uuid        uuid.UUID      `json:"uuid"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Content     string         `json:"content"`
	ImageUrl    sql.NullString `json:"image_url"`
	VideoUrl    sql.NullString `json:"video_url"`
	Category    sql.NullString `json:"category"`
	Published   bool           `json:"published"`
	OrderNumber int32          `json:"order_number"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID                int64          `json:"id"`
	Uuid              uuid.UUID      `json:"uuid"`
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	FullName          string         `json:"full_name"`
	Email             string         `json:"email"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	ProfileImage      sql.NullString `json:"profile_image"`
}

type UserAcceptedTerm struct {
	ID              int64     `json:"id"`
	Uuid            uuid.UUID `json:"uuid"`
	UserID          int64     `json:"user_id"`
	LegalDocumentID int64     `json:"legal_document_id"`
	AcceptedAt      time.Time `json:"accepted_at"`
}
