// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_identity.sql

package db

import (
	"context"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (
  user_id,
  provider,
  provider_subject,
  email,
  email_verified
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, uuid, user_id, provider, provider_subject, email, email_verified, created_at, updated_at
`

type CreateOAuthIdentityParams struct {
	UserID          int64  `json:"user_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
	EmailVerified   bool   `json:"email_verified"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, createOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.EmailVerified,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthIdentityByProviderAndSubject = `-- name: GetOAuthIdentityByProviderAndSubject :one
SELECT id, uuid, user_id, provider, provider_subject, email, email_verified, created_at, updated_at
FROM oauth_identities
WHERE provider = $1 AND provider_subject = $2
LIMIT 1
`

type GetOAuthIdentityByProviderAndSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetOAuthIdentityByProviderAndSubject(ctx context.Context, arg GetOAuthIdentityByProviderAndSubjectParams) (OauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOAuthIdentityByProviderAndSubject, arg.Provider, arg.ProviderSubject)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
