// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateIrrigationAction(ctx context.Context, arg CreateIrrigationActionParams) (IrrigationAction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteIrrigationAction(ctx context.Context, id int64) error
	GetDevice(ctx context.Context, argUuid uuid.UUID) (Device, error)
	GetDeviceForUpdate(ctx context.Context, argUuid uuid.UUID) (Device, error)
	GetIrrigationAction(ctx context.Context, argUuid uuid.UUID) (IrrigationAction, error)
	GetUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	LinkDeviceToUserByQrToken(ctx context.Context, arg LinkDeviceToUserByQrTokenParams) (Device, error)
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	ListIrrigationAction(ctx context.Context, arg ListIrrigationActionParams) ([]IrrigationAction, error)
	UnlinkDeviceFromUser(ctx context.Context, arg UnlinkDeviceFromUserParams) (Device, error)
	UpdateDevices(ctx context.Context, arg UpdateDevicesParams) (Device, error)
	UpdateIrrigationAction(ctx context.Context, arg UpdateIrrigationActionParams) (IrrigationAction, error)
	UpdateNameDevice(ctx context.Context, arg UpdateNameDeviceParams) (Device, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
