// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tutorials.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getTutorial = `-- name: GetTutorial :one
SELECT id, uuid, title, description, content, image_url, video_url, category, published, order_number, created_at, updated_at
FROM tutorials
WHERE uuid = $1
AND published = true
LIMIT 1
`

func (q *Queries) GetTutorial(ctx context.Context, argUuid uuid.UUID) (Tutorial, error) {
	row := q.db.QueryRowContext(ctx, getTutorial, argUuid)
	var i Tutorial
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.ImageUrl,
		&i.VideoUrl,
		&i.Category,
		&i.Published,
		&i.OrderNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTutorials = `-- name: ListTutorials :many
SELECT id, uuid, title, description, content, image_url, video_url, category, published, order_number, created_at, updated_at
FROM tutorials
WHERE published = true
ORDER BY order_number ASC
LIMIT $1
OFFSET $2
`

type ListTutorialsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTutorials(ctx context.Context, arg ListTutorialsParams) ([]Tutorial, error) {
	rows, err := q.db.QueryContext(ctx, listTutorials, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tutorial{}
	for rows.Next() {
		var i Tutorial
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.ImageUrl,
			&i.VideoUrl,
			&i.Category,
			&i.Published,
			&i.OrderNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTutorialsByCategory = `-- name: ListTutorialsByCategory :many
SELECT id, uuid, title, description, content, image_url, video_url, category, published, order_number, created_at, updated_at
FROM tutorials
WHERE category = $1
AND published = true
ORDER BY order_number ASC
LIMIT $2
OFFSET $3
`

type ListTutorialsByCategoryParams struct {
	Category sql.NullString `json:"category"`
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
}

func (q *Queries) ListTutorialsByCategory(ctx context.Context, arg ListTutorialsByCategoryParams) ([]Tutorial, error) {
	rows, err := q.db.QueryContext(ctx, listTutorialsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tutorial{}
	for rows.Next() {
		var i Tutorial
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.ImageUrl,
			&i.VideoUrl,
			&i.Category,
			&i.Published,
			&i.OrderNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
