// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_accepted_terms.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserAcceptedTerm = `-- name: CreateUserAcceptedTerm :one
INSERT INTO user_accepted_terms (
  user_id, 
  legal_document_id
) VALUES (
  $1, $2
) RETURNING id, uuid, user_id, legal_document_id, accepted_at
`

type CreateUserAcceptedTermParams struct {
	UserID          int64 `json:"user_id"`
	LegalDocumentID int64 `json:"legal_document_id"`
}

func (q *Queries) CreateUserAcceptedTerm(ctx context.Context, arg CreateUserAcceptedTermParams) (UserAcceptedTerm, error) {
	row := q.db.QueryRowContext(ctx, createUserAcceptedTerm, arg.UserID, arg.LegalDocumentID)
	var i UserAcceptedTerm
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LegalDocumentID,
		&i.AcceptedAt,
	)
	return i, err
}

const getUserAcceptedTerm = `-- name: GetUserAcceptedTerm :one
SELECT id, uuid, user_id, legal_document_id, accepted_at FROM user_accepted_terms
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetUserAcceptedTerm(ctx context.Context, argUuid uuid.UUID) (UserAcceptedTerm, error) {
	row := q.db.QueryRowContext(ctx, getUserAcceptedTerm, argUuid)
	var i UserAcceptedTerm
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LegalDocumentID,
		&i.AcceptedAt,
	)
	return i, err
}

const getUserAcceptedTermByLegalDocument = `-- name: GetUserAcceptedTermByLegalDocument :one
SELECT id, uuid, user_id, legal_document_id, accepted_at FROM user_accepted_terms
WHERE legal_document_id = $1 LIMIT 1
`

func (q *Queries) GetUserAcceptedTermByLegalDocument(ctx context.Context, legalDocumentID int64) (UserAcceptedTerm, error) {
	row := q.db.QueryRowContext(ctx, getUserAcceptedTermByLegalDocument, legalDocumentID)
	var i UserAcceptedTerm
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LegalDocumentID,
		&i.AcceptedAt,
	)
	return i, err
}

const getUserAcceptedTermByUser = `-- name: GetUserAcceptedTermByUser :one
SELECT id, uuid, user_id, legal_document_id, accepted_at FROM user_accepted_terms
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserAcceptedTermByUser(ctx context.Context, userID int64) (UserAcceptedTerm, error) {
	row := q.db.QueryRowContext(ctx, getUserAcceptedTermByUser, userID)
	var i UserAcceptedTerm
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LegalDocumentID,
		&i.AcceptedAt,
	)
	return i, err
}
