// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  hashed_password,
  full_name,
  email,
  profile_image
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, uuid, username, hashed_password, full_name, email, password_changed_at, created_at, profile_image
`

type CreateUserParams struct {
	Username       string         `json:"username"`
	HashedPassword string         `json:"hashed_password"`
	FullName       string         `json:"full_name"`
	Email          string         `json:"email"`
	ProfileImage   sql.NullString `json:"profile_image"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
		arg.ProfileImage,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ProfileImage,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, uuid, username, hashed_password, full_name, email, password_changed_at, created_at, profile_image FROM users
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ProfileImage,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, username, hashed_password, full_name, email, password_changed_at, created_at, profile_image FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ProfileImage,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, username, hashed_password, full_name, email, password_changed_at, created_at, profile_image FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ProfileImage,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET full_name = $2
WHERE uuid = $1
RETURNING id, uuid, username, hashed_password, full_name, email, password_changed_at, created_at, profile_image
`

type UpdateUserNameParams struct {
	Uuid     uuid.UUID `json:"uuid"`
	FullName string    `json:"full_name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserName, arg.Uuid, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ProfileImage,
	)
	return i, err
}

const updateUserProfileImage = `-- name: UpdateUserProfileImage :one
UPDATE users
SET profile_image = $2
WHERE uuid = $1
RETURNING id, uuid, username, hashed_password, full_name, email, password_changed_at, created_at, profile_image
`

type UpdateUserProfileImageParams struct {
	Uuid         uuid.UUID      `json:"uuid"`
	ProfileImage sql.NullString `json:"profile_image"`
}

func (q *Queries) UpdateUserProfileImage(ctx context.Context, arg UpdateUserProfileImageParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfileImage, arg.Uuid, arg.ProfileImage)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ProfileImage,
	)
	return i, err
}
