// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Teixeiraass/ground_guard_be/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/Teixeiraass/ground_guard_be/db/sqlc"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// BlockSession mocks base method.
func (m *MockStore) BlockSession(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockSession indicates an expected call of BlockSession.
func (mr *MockStoreMockRecorder) BlockSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSession", reflect.TypeOf((*MockStore)(nil).BlockSession), arg0, arg1)
}

// CreateDevice mocks base method.
func (m *MockStore) CreateDevice(arg0 context.Context, arg1 db.CreateDeviceParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockStoreMockRecorder) CreateDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockStore)(nil).CreateDevice), arg0, arg1)
}

// CreateIrrigationAction mocks base method.
func (m *MockStore) CreateIrrigationAction(arg0 context.Context, arg1 db.CreateIrrigationActionParams) (db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIrrigationAction indicates an expected call of CreateIrrigationAction.
func (mr *MockStoreMockRecorder) CreateIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIrrigationAction", reflect.TypeOf((*MockStore)(nil).CreateIrrigationAction), arg0, arg1)
}

// CreateIrrigationCommand mocks base method.
func (m *MockStore) CreateIrrigationCommand(arg0 context.Context, arg1 db.CreateIrrigationCommandParams) (db.IrrigationCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIrrigationCommand", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIrrigationCommand indicates an expected call of CreateIrrigationCommand.
func (mr *MockStoreMockRecorder) CreateIrrigationCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIrrigationCommand", reflect.TypeOf((*MockStore)(nil).CreateIrrigationCommand), arg0, arg1)
}

// CreateIrrigationPreferenceHistory mocks base method.
func (m *MockStore) CreateIrrigationPreferenceHistory(arg0 context.Context, arg1 db.CreateIrrigationPreferenceHistoryParams) (db.IrrigationPreferencesHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIrrigationPreferenceHistory", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationPreferencesHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIrrigationPreferenceHistory indicates an expected call of CreateIrrigationPreferenceHistory.
func (mr *MockStoreMockRecorder) CreateIrrigationPreferenceHistory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIrrigationPreferenceHistory", reflect.TypeOf((*MockStore)(nil).CreateIrrigationPreferenceHistory), arg0, arg1)
}

// CreateIrrigationPreferences mocks base method.
func (m *MockStore) CreateIrrigationPreferences(arg0 context.Context, arg1 db.CreateIrrigationPreferencesParams) (db.IrrigationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIrrigationPreferences", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIrrigationPreferences indicates an expected call of CreateIrrigationPreferences.
func (mr *MockStoreMockRecorder) CreateIrrigationPreferences(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIrrigationPreferences", reflect.TypeOf((*MockStore)(nil).CreateIrrigationPreferences), arg0, arg1)
}

// CreateOAuthIdentity mocks base method.
func (m *MockStore) CreateOAuthIdentity(arg0 context.Context, arg1 db.CreateOAuthIdentityParams) (db.OauthIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOAuthIdentity", arg0, arg1)
	ret0, _ := ret[0].(db.OauthIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOAuthIdentity indicates an expected call of CreateOAuthIdentity.
func (mr *MockStoreMockRecorder) CreateOAuthIdentity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuthIdentity", reflect.TypeOf((*MockStore)(nil).CreateOAuthIdentity), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserAcceptedTerm mocks base method.
func (m *MockStore) CreateUserAcceptedTerm(arg0 context.Context, arg1 db.CreateUserAcceptedTermParams) (db.UserAcceptedTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAcceptedTerm", arg0, arg1)
	ret0, _ := ret[0].(db.UserAcceptedTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAcceptedTerm indicates an expected call of CreateUserAcceptedTerm.
func (mr *MockStoreMockRecorder) CreateUserAcceptedTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAcceptedTerm", reflect.TypeOf((*MockStore)(nil).CreateUserAcceptedTerm), arg0, arg1)
}

// DeleteIrrigationAction mocks base method.
func (m *MockStore) DeleteIrrigationAction(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIrrigationAction indicates an expected call of DeleteIrrigationAction.
func (mr *MockStoreMockRecorder) DeleteIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIrrigationAction", reflect.TypeOf((*MockStore)(nil).DeleteIrrigationAction), arg0, arg1)
}

// DeleteIrrigationCommand mocks base method.
func (m *MockStore) DeleteIrrigationCommand(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIrrigationCommand", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIrrigationCommand indicates an expected call of DeleteIrrigationCommand.
func (mr *MockStoreMockRecorder) DeleteIrrigationCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIrrigationCommand", reflect.TypeOf((*MockStore)(nil).DeleteIrrigationCommand), arg0, arg1)
}

// DeleteIrrigationPreference mocks base method.
func (m *MockStore) DeleteIrrigationPreference(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIrrigationPreference", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIrrigationPreference indicates an expected call of DeleteIrrigationPreference.
func (mr *MockStoreMockRecorder) DeleteIrrigationPreference(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIrrigationPreference", reflect.TypeOf((*MockStore)(nil).DeleteIrrigationPreference), arg0, arg1)
}

// DeleteIrrigationPreferenceByDeviceId mocks base method.
func (m *MockStore) DeleteIrrigationPreferenceByDeviceId(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIrrigationPreferenceByDeviceId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIrrigationPreferenceByDeviceId indicates an expected call of DeleteIrrigationPreferenceByDeviceId.
func (mr *MockStoreMockRecorder) DeleteIrrigationPreferenceByDeviceId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIrrigationPreferenceByDeviceId", reflect.TypeOf((*MockStore)(nil).DeleteIrrigationPreferenceByDeviceId), arg0, arg1)
}

// ExistsActiveIrrigationAction mocks base method.
func (m *MockStore) ExistsActiveIrrigationAction(arg0 context.Context, arg1 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsActiveIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsActiveIrrigationAction indicates an expected call of ExistsActiveIrrigationAction.
func (mr *MockStoreMockRecorder) ExistsActiveIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsActiveIrrigationAction", reflect.TypeOf((*MockStore)(nil).ExistsActiveIrrigationAction), arg0, arg1)
}

// ExistsPendingIrrigationCommand mocks base method.
func (m *MockStore) ExistsPendingIrrigationCommand(arg0 context.Context, arg1 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsPendingIrrigationCommand", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsPendingIrrigationCommand indicates an expected call of ExistsPendingIrrigationCommand.
func (mr *MockStoreMockRecorder) ExistsPendingIrrigationCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsPendingIrrigationCommand", reflect.TypeOf((*MockStore)(nil).ExistsPendingIrrigationCommand), arg0, arg1)
}

// FailTimedOutCommands mocks base method.
func (m *MockStore) FailTimedOutCommands(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailTimedOutCommands", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailTimedOutCommands indicates an expected call of FailTimedOutCommands.
func (mr *MockStoreMockRecorder) FailTimedOutCommands(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailTimedOutCommands", reflect.TypeOf((*MockStore)(nil).FailTimedOutCommands), arg0)
}

// GetActiveIrrigationActionByDevice mocks base method.
func (m *MockStore) GetActiveIrrigationActionByDevice(arg0 context.Context, arg1 int64) (db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveIrrigationActionByDevice", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveIrrigationActionByDevice indicates an expected call of GetActiveIrrigationActionByDevice.
func (mr *MockStoreMockRecorder) GetActiveIrrigationActionByDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveIrrigationActionByDevice", reflect.TypeOf((*MockStore)(nil).GetActiveIrrigationActionByDevice), arg0, arg1)
}

// GetDevice mocks base method.
func (m *MockStore) GetDevice(arg0 context.Context, arg1 uuid.UUID) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockStoreMockRecorder) GetDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockStore)(nil).GetDevice), arg0, arg1)
}

// GetDeviceByUID mocks base method.
func (m *MockStore) GetDeviceByUID(arg0 context.Context, arg1 string) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByUID", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByUID indicates an expected call of GetDeviceByUID.
func (mr *MockStoreMockRecorder) GetDeviceByUID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByUID", reflect.TypeOf((*MockStore)(nil).GetDeviceByUID), arg0, arg1)
}

// GetDeviceForUpdate mocks base method.
func (m *MockStore) GetDeviceForUpdate(arg0 context.Context, arg1 uuid.UUID) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceForUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceForUpdate indicates an expected call of GetDeviceForUpdate.
func (mr *MockStoreMockRecorder) GetDeviceForUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceForUpdate", reflect.TypeOf((*MockStore)(nil).GetDeviceForUpdate), arg0, arg1)
}

// GetFaq mocks base method.
func (m *MockStore) GetFaq(arg0 context.Context, arg1 uuid.UUID) (db.Faq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFaq", arg0, arg1)
	ret0, _ := ret[0].(db.Faq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFaq indicates an expected call of GetFaq.
func (mr *MockStoreMockRecorder) GetFaq(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFaq", reflect.TypeOf((*MockStore)(nil).GetFaq), arg0, arg1)
}

// GetHelpContent mocks base method.
func (m *MockStore) GetHelpContent(arg0 context.Context, arg1 uuid.UUID) (db.HelpContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelpContent", arg0, arg1)
	ret0, _ := ret[0].(db.HelpContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHelpContent indicates an expected call of GetHelpContent.
func (mr *MockStoreMockRecorder) GetHelpContent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelpContent", reflect.TypeOf((*MockStore)(nil).GetHelpContent), arg0, arg1)
}

// GetIrrigationAction mocks base method.
func (m *MockStore) GetIrrigationAction(arg0 context.Context, arg1 uuid.UUID) (db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIrrigationAction indicates an expected call of GetIrrigationAction.
func (mr *MockStoreMockRecorder) GetIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIrrigationAction", reflect.TypeOf((*MockStore)(nil).GetIrrigationAction), arg0, arg1)
}

// GetIrrigationCommand mocks base method.
func (m *MockStore) GetIrrigationCommand(arg0 context.Context, arg1 uuid.UUID) (db.IrrigationCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIrrigationCommand", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIrrigationCommand indicates an expected call of GetIrrigationCommand.
func (mr *MockStoreMockRecorder) GetIrrigationCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIrrigationCommand", reflect.TypeOf((*MockStore)(nil).GetIrrigationCommand), arg0, arg1)
}

// GetIrrigationPreference mocks base method.
func (m *MockStore) GetIrrigationPreference(arg0 context.Context, arg1 uuid.UUID) (db.IrrigationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIrrigationPreference", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIrrigationPreference indicates an expected call of GetIrrigationPreference.
func (mr *MockStoreMockRecorder) GetIrrigationPreference(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIrrigationPreference", reflect.TypeOf((*MockStore)(nil).GetIrrigationPreference), arg0, arg1)
}

// GetIrrigationPreferenceByDevice mocks base method.
func (m *MockStore) GetIrrigationPreferenceByDevice(arg0 context.Context, arg1 int64) (db.IrrigationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIrrigationPreferenceByDevice", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIrrigationPreferenceByDevice indicates an expected call of GetIrrigationPreferenceByDevice.
func (mr *MockStoreMockRecorder) GetIrrigationPreferenceByDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIrrigationPreferenceByDevice", reflect.TypeOf((*MockStore)(nil).GetIrrigationPreferenceByDevice), arg0, arg1)
}

// GetLegalDocument mocks base method.
func (m *MockStore) GetLegalDocument(arg0 context.Context, arg1 uuid.UUID) (db.LegalDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLegalDocument", arg0, arg1)
	ret0, _ := ret[0].(db.LegalDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLegalDocument indicates an expected call of GetLegalDocument.
func (mr *MockStoreMockRecorder) GetLegalDocument(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLegalDocument", reflect.TypeOf((*MockStore)(nil).GetLegalDocument), arg0, arg1)
}

// GetOAuthIdentityByProviderAndSubject mocks base method.
func (m *MockStore) GetOAuthIdentityByProviderAndSubject(arg0 context.Context, arg1 db.GetOAuthIdentityByProviderAndSubjectParams) (db.OauthIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthIdentityByProviderAndSubject", arg0, arg1)
	ret0, _ := ret[0].(db.OauthIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthIdentityByProviderAndSubject indicates an expected call of GetOAuthIdentityByProviderAndSubject.
func (mr *MockStoreMockRecorder) GetOAuthIdentityByProviderAndSubject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthIdentityByProviderAndSubject", reflect.TypeOf((*MockStore)(nil).GetOAuthIdentityByProviderAndSubject), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), arg0, arg1)
}

// GetTutorial mocks base method.
func (m *MockStore) GetTutorial(arg0 context.Context, arg1 uuid.UUID) (db.Tutorial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTutorial", arg0, arg1)
	ret0, _ := ret[0].(db.Tutorial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTutorial indicates an expected call of GetTutorial.
func (mr *MockStoreMockRecorder) GetTutorial(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTutorial", reflect.TypeOf((*MockStore)(nil).GetTutorial), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 uuid.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserAcceptedTerm mocks base method.
func (m *MockStore) GetUserAcceptedTerm(arg0 context.Context, arg1 uuid.UUID) (db.UserAcceptedTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAcceptedTerm", arg0, arg1)
	ret0, _ := ret[0].(db.UserAcceptedTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAcceptedTerm indicates an expected call of GetUserAcceptedTerm.
func (mr *MockStoreMockRecorder) GetUserAcceptedTerm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAcceptedTerm", reflect.TypeOf((*MockStore)(nil).GetUserAcceptedTerm), arg0, arg1)
}

// GetUserAcceptedTermByLegalDocument mocks base method.
func (m *MockStore) GetUserAcceptedTermByLegalDocument(arg0 context.Context, arg1 int64) (db.UserAcceptedTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAcceptedTermByLegalDocument", arg0, arg1)
	ret0, _ := ret[0].(db.UserAcceptedTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAcceptedTermByLegalDocument indicates an expected call of GetUserAcceptedTermByLegalDocument.
func (mr *MockStoreMockRecorder) GetUserAcceptedTermByLegalDocument(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAcceptedTermByLegalDocument", reflect.TypeOf((*MockStore)(nil).GetUserAcceptedTermByLegalDocument), arg0, arg1)
}

// GetUserAcceptedTermByUser mocks base method.
func (m *MockStore) GetUserAcceptedTermByUser(arg0 context.Context, arg1 int64) (db.UserAcceptedTerm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAcceptedTermByUser", arg0, arg1)
	ret0, _ := ret[0].(db.UserAcceptedTerm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAcceptedTermByUser indicates an expected call of GetUserAcceptedTermByUser.
func (mr *MockStoreMockRecorder) GetUserAcceptedTermByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAcceptedTermByUser", reflect.TypeOf((*MockStore)(nil).GetUserAcceptedTermByUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(arg0 context.Context, arg1 int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), arg0, arg1)
}

// LinkDeviceToUserByQrToken mocks base method.
func (m *MockStore) LinkDeviceToUserByQrToken(arg0 context.Context, arg1 db.LinkDeviceToUserByQrTokenParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkDeviceToUserByQrToken", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkDeviceToUserByQrToken indicates an expected call of LinkDeviceToUserByQrToken.
func (mr *MockStoreMockRecorder) LinkDeviceToUserByQrToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkDeviceToUserByQrToken", reflect.TypeOf((*MockStore)(nil).LinkDeviceToUserByQrToken), arg0, arg1)
}

// LinkIrrigationCommandAction mocks base method.
func (m *MockStore) LinkIrrigationCommandAction(arg0 context.Context, arg1 db.LinkIrrigationCommandActionParams) (db.IrrigationCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkIrrigationCommandAction", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkIrrigationCommandAction indicates an expected call of LinkIrrigationCommandAction.
func (mr *MockStoreMockRecorder) LinkIrrigationCommandAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkIrrigationCommandAction", reflect.TypeOf((*MockStore)(nil).LinkIrrigationCommandAction), arg0, arg1)
}

// ListDevices mocks base method.
func (m *MockStore) ListDevices(arg0 context.Context, arg1 db.ListDevicesParams) ([]db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevices", arg0, arg1)
	ret0, _ := ret[0].([]db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockStoreMockRecorder) ListDevices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockStore)(nil).ListDevices), arg0, arg1)
}

// ListFaqs mocks base method.
func (m *MockStore) ListFaqs(arg0 context.Context, arg1 db.ListFaqsParams) ([]db.Faq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFaqs", arg0, arg1)
	ret0, _ := ret[0].([]db.Faq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFaqs indicates an expected call of ListFaqs.
func (mr *MockStoreMockRecorder) ListFaqs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFaqs", reflect.TypeOf((*MockStore)(nil).ListFaqs), arg0, arg1)
}

// ListHelpContents mocks base method.
func (m *MockStore) ListHelpContents(arg0 context.Context, arg1 db.ListHelpContentsParams) ([]db.HelpContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHelpContents", arg0, arg1)
	ret0, _ := ret[0].([]db.HelpContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHelpContents indicates an expected call of ListHelpContents.
func (mr *MockStoreMockRecorder) ListHelpContents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHelpContents", reflect.TypeOf((*MockStore)(nil).ListHelpContents), arg0, arg1)
}

// ListHelpContentsByCategory mocks base method.
func (m *MockStore) ListHelpContentsByCategory(arg0 context.Context, arg1 db.ListHelpContentsByCategoryParams) ([]db.HelpContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHelpContentsByCategory", arg0, arg1)
	ret0, _ := ret[0].([]db.HelpContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHelpContentsByCategory indicates an expected call of ListHelpContentsByCategory.
func (mr *MockStoreMockRecorder) ListHelpContentsByCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHelpContentsByCategory", reflect.TypeOf((*MockStore)(nil).ListHelpContentsByCategory), arg0, arg1)
}

// ListIrrigationAction mocks base method.
func (m *MockStore) ListIrrigationAction(arg0 context.Context, arg1 db.ListIrrigationActionParams) ([]db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].([]db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIrrigationAction indicates an expected call of ListIrrigationAction.
func (mr *MockStoreMockRecorder) ListIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIrrigationAction", reflect.TypeOf((*MockStore)(nil).ListIrrigationAction), arg0, arg1)
}

// ListIrrigationCommands mocks base method.
func (m *MockStore) ListIrrigationCommands(arg0 context.Context, arg1 db.ListIrrigationCommandsParams) ([]db.IrrigationCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIrrigationCommands", arg0, arg1)
	ret0, _ := ret[0].([]db.IrrigationCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIrrigationCommands indicates an expected call of ListIrrigationCommands.
func (mr *MockStoreMockRecorder) ListIrrigationCommands(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIrrigationCommands", reflect.TypeOf((*MockStore)(nil).ListIrrigationCommands), arg0, arg1)
}

// ListIrrigationPreferences mocks base method.
func (m *MockStore) ListIrrigationPreferences(arg0 context.Context, arg1 db.ListIrrigationPreferencesParams) ([]db.IrrigationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIrrigationPreferences", arg0, arg1)
	ret0, _ := ret[0].([]db.IrrigationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIrrigationPreferences indicates an expected call of ListIrrigationPreferences.
func (mr *MockStoreMockRecorder) ListIrrigationPreferences(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIrrigationPreferences", reflect.TypeOf((*MockStore)(nil).ListIrrigationPreferences), arg0, arg1)
}

// ListLegalDocuments mocks base method.
func (m *MockStore) ListLegalDocuments(arg0 context.Context, arg1 db.ListLegalDocumentsParams) ([]db.LegalDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLegalDocuments", arg0, arg1)
	ret0, _ := ret[0].([]db.LegalDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLegalDocuments indicates an expected call of ListLegalDocuments.
func (mr *MockStoreMockRecorder) ListLegalDocuments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLegalDocuments", reflect.TypeOf((*MockStore)(nil).ListLegalDocuments), arg0, arg1)
}

// ListTutorials mocks base method.
func (m *MockStore) ListTutorials(arg0 context.Context, arg1 db.ListTutorialsParams) ([]db.Tutorial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTutorials", arg0, arg1)
	ret0, _ := ret[0].([]db.Tutorial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTutorials indicates an expected call of ListTutorials.
func (mr *MockStoreMockRecorder) ListTutorials(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTutorials", reflect.TypeOf((*MockStore)(nil).ListTutorials), arg0, arg1)
}

// ListTutorialsByCategory mocks base method.
func (m *MockStore) ListTutorialsByCategory(arg0 context.Context, arg1 db.ListTutorialsByCategoryParams) ([]db.Tutorial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTutorialsByCategory", arg0, arg1)
	ret0, _ := ret[0].([]db.Tutorial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTutorialsByCategory indicates an expected call of ListTutorialsByCategory.
func (mr *MockStoreMockRecorder) ListTutorialsByCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTutorialsByCategory", reflect.TypeOf((*MockStore)(nil).ListTutorialsByCategory), arg0, arg1)
}

// UnlinkDeviceFromUser mocks base method.
func (m *MockStore) UnlinkDeviceFromUser(arg0 context.Context, arg1 db.UnlinkDeviceFromUserParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkDeviceFromUser", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlinkDeviceFromUser indicates an expected call of UnlinkDeviceFromUser.
func (mr *MockStoreMockRecorder) UnlinkDeviceFromUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkDeviceFromUser", reflect.TypeOf((*MockStore)(nil).UnlinkDeviceFromUser), arg0, arg1)
}

// UpdateDeviceRegistration mocks base method.
func (m *MockStore) UpdateDeviceRegistration(arg0 context.Context, arg1 db.UpdateDeviceRegistrationParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceRegistration", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeviceRegistration indicates an expected call of UpdateDeviceRegistration.
func (mr *MockStoreMockRecorder) UpdateDeviceRegistration(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceRegistration", reflect.TypeOf((*MockStore)(nil).UpdateDeviceRegistration), arg0, arg1)
}

// UpdateDeviceTelemetryByUID mocks base method.
func (m *MockStore) UpdateDeviceTelemetryByUID(arg0 context.Context, arg1 db.UpdateDeviceTelemetryByUIDParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceTelemetryByUID", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeviceTelemetryByUID indicates an expected call of UpdateDeviceTelemetryByUID.
func (mr *MockStoreMockRecorder) UpdateDeviceTelemetryByUID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceTelemetryByUID", reflect.TypeOf((*MockStore)(nil).UpdateDeviceTelemetryByUID), arg0, arg1)
}

// UpdateDevices mocks base method.
func (m *MockStore) UpdateDevices(arg0 context.Context, arg1 db.UpdateDevicesParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevices", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevices indicates an expected call of UpdateDevices.
func (mr *MockStoreMockRecorder) UpdateDevices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevices", reflect.TypeOf((*MockStore)(nil).UpdateDevices), arg0, arg1)
}

// UpdateIrrigationAction mocks base method.
func (m *MockStore) UpdateIrrigationAction(arg0 context.Context, arg1 db.UpdateIrrigationActionParams) (db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIrrigationAction indicates an expected call of UpdateIrrigationAction.
func (mr *MockStoreMockRecorder) UpdateIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIrrigationAction", reflect.TypeOf((*MockStore)(nil).UpdateIrrigationAction), arg0, arg1)
}

// UpdateIrrigationCommandStatus mocks base method.
func (m *MockStore) UpdateIrrigationCommandStatus(arg0 context.Context, arg1 db.UpdateIrrigationCommandStatusParams) (db.IrrigationCommand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIrrigationCommandStatus", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationCommand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIrrigationCommandStatus indicates an expected call of UpdateIrrigationCommandStatus.
func (mr *MockStoreMockRecorder) UpdateIrrigationCommandStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIrrigationCommandStatus", reflect.TypeOf((*MockStore)(nil).UpdateIrrigationCommandStatus), arg0, arg1)
}

// UpdateIrrigationPreference mocks base method.
func (m *MockStore) UpdateIrrigationPreference(arg0 context.Context, arg1 db.UpdateIrrigationPreferenceParams) (db.IrrigationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIrrigationPreference", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIrrigationPreference indicates an expected call of UpdateIrrigationPreference.
func (mr *MockStoreMockRecorder) UpdateIrrigationPreference(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIrrigationPreference", reflect.TypeOf((*MockStore)(nil).UpdateIrrigationPreference), arg0, arg1)
}

// UpdateNameDevice mocks base method.
func (m *MockStore) UpdateNameDevice(arg0 context.Context, arg1 db.UpdateNameDeviceParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNameDevice", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNameDevice indicates an expected call of UpdateNameDevice.
func (mr *MockStoreMockRecorder) UpdateNameDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNameDevice", reflect.TypeOf((*MockStore)(nil).UpdateNameDevice), arg0, arg1)
}

// UpdateUserName mocks base method.
func (m *MockStore) UpdateUserName(arg0 context.Context, arg1 db.UpdateUserNameParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserName", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserName indicates an expected call of UpdateUserName.
func (mr *MockStoreMockRecorder) UpdateUserName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserName", reflect.TypeOf((*MockStore)(nil).UpdateUserName), arg0, arg1)
}

// UpdateUserProfileImage mocks base method.
func (m *MockStore) UpdateUserProfileImage(arg0 context.Context, arg1 db.UpdateUserProfileImageParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfileImage", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfileImage indicates an expected call of UpdateUserProfileImage.
func (mr *MockStoreMockRecorder) UpdateUserProfileImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfileImage", reflect.TypeOf((*MockStore)(nil).UpdateUserProfileImage), arg0, arg1)
}
