// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Teixeiraass/ground_guard_be/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/Teixeiraass/ground_guard_be/db/sqlc"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateDevice mocks base method.
func (m *MockStore) CreateDevice(arg0 context.Context, arg1 db.CreateDeviceParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockStoreMockRecorder) CreateDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockStore)(nil).CreateDevice), arg0, arg1)
}

// CreateIrrigationAction mocks base method.
func (m *MockStore) CreateIrrigationAction(arg0 context.Context, arg1 db.CreateIrrigationActionParams) (db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIrrigationAction indicates an expected call of CreateIrrigationAction.
func (mr *MockStoreMockRecorder) CreateIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIrrigationAction", reflect.TypeOf((*MockStore)(nil).CreateIrrigationAction), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// DeleteIrrigationAction mocks base method.
func (m *MockStore) DeleteIrrigationAction(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIrrigationAction indicates an expected call of DeleteIrrigationAction.
func (mr *MockStoreMockRecorder) DeleteIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIrrigationAction", reflect.TypeOf((*MockStore)(nil).DeleteIrrigationAction), arg0, arg1)
}

// GetDevice mocks base method.
func (m *MockStore) GetDevice(arg0 context.Context, arg1 uuid.UUID) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockStoreMockRecorder) GetDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockStore)(nil).GetDevice), arg0, arg1)
}

// GetDeviceForUpdate mocks base method.
func (m *MockStore) GetDeviceForUpdate(arg0 context.Context, arg1 uuid.UUID) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceForUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceForUpdate indicates an expected call of GetDeviceForUpdate.
func (mr *MockStoreMockRecorder) GetDeviceForUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceForUpdate", reflect.TypeOf((*MockStore)(nil).GetDeviceForUpdate), arg0, arg1)
}

// GetIrrigationAction mocks base method.
func (m *MockStore) GetIrrigationAction(arg0 context.Context, arg1 uuid.UUID) (db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIrrigationAction indicates an expected call of GetIrrigationAction.
func (mr *MockStoreMockRecorder) GetIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIrrigationAction", reflect.TypeOf((*MockStore)(nil).GetIrrigationAction), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 uuid.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// LinkDeviceToUserByQrToken mocks base method.
func (m *MockStore) LinkDeviceToUserByQrToken(arg0 context.Context, arg1 db.LinkDeviceToUserByQrTokenParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkDeviceToUserByQrToken", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkDeviceToUserByQrToken indicates an expected call of LinkDeviceToUserByQrToken.
func (mr *MockStoreMockRecorder) LinkDeviceToUserByQrToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkDeviceToUserByQrToken", reflect.TypeOf((*MockStore)(nil).LinkDeviceToUserByQrToken), arg0, arg1)
}

// ListDevices mocks base method.
func (m *MockStore) ListDevices(arg0 context.Context, arg1 db.ListDevicesParams) ([]db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevices", arg0, arg1)
	ret0, _ := ret[0].([]db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockStoreMockRecorder) ListDevices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockStore)(nil).ListDevices), arg0, arg1)
}

// ListIrrigationAction mocks base method.
func (m *MockStore) ListIrrigationAction(arg0 context.Context, arg1 db.ListIrrigationActionParams) ([]db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].([]db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIrrigationAction indicates an expected call of ListIrrigationAction.
func (mr *MockStoreMockRecorder) ListIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIrrigationAction", reflect.TypeOf((*MockStore)(nil).ListIrrigationAction), arg0, arg1)
}

// UnlinkDeviceFromUser mocks base method.
func (m *MockStore) UnlinkDeviceFromUser(arg0 context.Context, arg1 db.UnlinkDeviceFromUserParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkDeviceFromUser", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlinkDeviceFromUser indicates an expected call of UnlinkDeviceFromUser.
func (mr *MockStoreMockRecorder) UnlinkDeviceFromUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkDeviceFromUser", reflect.TypeOf((*MockStore)(nil).UnlinkDeviceFromUser), arg0, arg1)
}

// UpdateDevices mocks base method.
func (m *MockStore) UpdateDevices(arg0 context.Context, arg1 db.UpdateDevicesParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevices", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevices indicates an expected call of UpdateDevices.
func (mr *MockStoreMockRecorder) UpdateDevices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevices", reflect.TypeOf((*MockStore)(nil).UpdateDevices), arg0, arg1)
}

// UpdateIrrigationAction mocks base method.
func (m *MockStore) UpdateIrrigationAction(arg0 context.Context, arg1 db.UpdateIrrigationActionParams) (db.IrrigationAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIrrigationAction", arg0, arg1)
	ret0, _ := ret[0].(db.IrrigationAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIrrigationAction indicates an expected call of UpdateIrrigationAction.
func (mr *MockStoreMockRecorder) UpdateIrrigationAction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIrrigationAction", reflect.TypeOf((*MockStore)(nil).UpdateIrrigationAction), arg0, arg1)
}

// UpdateNameDevice mocks base method.
func (m *MockStore) UpdateNameDevice(arg0 context.Context, arg1 db.UpdateNameDeviceParams) (db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNameDevice", arg0, arg1)
	ret0, _ := ret[0].(db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNameDevice indicates an expected call of UpdateNameDevice.
func (mr *MockStoreMockRecorder) UpdateNameDevice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNameDevice", reflect.TypeOf((*MockStore)(nil).UpdateNameDevice), arg0, arg1)
}

// UpdateUserName mocks base method.
func (m *MockStore) UpdateUserName(arg0 context.Context, arg1 db.UpdateUserNameParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserName", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserName indicates an expected call of UpdateUserName.
func (mr *MockStoreMockRecorder) UpdateUserName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserName", reflect.TypeOf((*MockStore)(nil).UpdateUserName), arg0, arg1)
}
